language: scala

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
  - rm ~/.m2/settings.xml
  - curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh

install: jabba install adopt@1.8.192-12 && jabba use $_ && java -version

  
jobs:
  include:
  - stage: test
    
    script: 
     - "bin/runSbtJob mixed-persistence/mixed-persistence-java-sbt test"
    name: "Run tests Mixed Persistence Java"  

  - script: 
    - "bin/runSbtJob mixed-persistence/mixed-persistence-scala-sbt test"
    name: "Run tests Mixed Persistence Scala"  

  - script:
    - "bin/runSbtJob grpc-example/grpc-example-java test"
    name: "Run tests gRPC example Java"

  - script:
    - "bin/runSbtJob grpc-example/grpc-example-scala test"
    name: "Run tests gRPC example Scala"

  - script:
    - docker-compose -f couchbase-persistence/docker/docker-compose.yml up -d couchbase 
    - sleep 20s
    - mvn -f couchbase-persistence/couchbase-persistence-java-mvn test
    name: "Run tests Couchbase Persistence Java" 

  - script:
    - docker-compose -f couchbase-persistence/docker/docker-compose.yml up -d couchbase 
    - sleep 20s
    - "bin/runSbtJob couchbase-persistence/couchbase-persistence-scala-sbt test"
    name: "Run tests Couchbase Persistence Scala"     

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.m2/repository
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aa0aeda88d31fe293d4
    on_success: change
    on_failure: always
    on_start: never
