language: scala

# Only build non-pushes (so PRs, API requests & cron jobs) OR forks OR main branch builds
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
if: type != push OR repo != lagom/lagom-samples OR branch IN (1.5.x, 1.6.x)

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
  - rm ~/.m2/settings.xml
  - . bin/jabbaLib && installJabba

services:
  # shopping cart is using postgres for testing
  - postgresql

jobs:
  include:
  - stage: test
    script: 
    - useAdoptOpenJdk8 
    - "bin/runSbtJob mixed-persistence/mixed-persistence-java-sbt test"
    name: "Run tests Mixed Persistence (java)"  
  - script: 
    - useAdoptOpenJdk8 
    - "bin/runSbtJob mixed-persistence/mixed-persistence-scala-sbt test"
    name: "Run tests Mixed Persistence (scala)"  

  - script:
    - useAdoptOpenJdk8 
    - "bin/runSbtJob grpc-example/grpc-example-java test"
    name: "Run tests gRPC example (java)"
  - script:
    - useAdoptOpenJdk8 
    - "bin/runSbtJob grpc-example/grpc-example-scala test"
    name: "Run tests gRPC example (scala)"

  - script:
    - useAdoptOpenJdk8 
    - "shopping-cart/travis-scripts/build.sh shopping-cart/shopping-cart-java sbt"
    name: "Run tests Shopping Cart example (java/sbt)"
  - script:
    - useAdoptOpenJdk8 
    - "shopping-cart/travis-scripts/build.sh shopping-cart/shopping-cart-java maven"
    name: "Run tests Shopping Cart example (java/mvn)"
  - script:
    - useAdoptOpenJdk8 
    - "shopping-cart/travis-scripts/build.sh shopping-cart/shopping-cart-scala sbt"
    name: "Run tests Shopping Cart example (scala)"

  - script:
    - docker-compose -f couchbase-persistence/docker/docker-compose.yml up -d couchbase 
    - sleep 30s
    - useAdoptOpenJdk8 
    - mvn -f couchbase-persistence/couchbase-persistence-java-mvn test
    name: "Run tests Couchbase Persistence (java)" 
  - script:
    - docker-compose -f couchbase-persistence/docker/docker-compose.yml up -d couchbase 
    - sleep 30s
    - useAdoptOpenJdk8 
    - "bin/runSbtJob couchbase-persistence/couchbase-persistence-scala-sbt test"
    name: "Run tests Couchbase Persistence (scala)"     


  - stage: test-java11
    script: 
    - useAdoptOpenJdk11
    - "bin/runSbtJob mixed-persistence/mixed-persistence-java-sbt test"
    name: "Run tests Mixed Persistence (java)"  
  - script: 
    - useAdoptOpenJdk11
    - "bin/runSbtJob mixed-persistence/mixed-persistence-scala-sbt test"
    name: "Run tests Mixed Persistence (scala)"  

  - script:
    - useAdoptOpenJdk11
    - "bin/runSbtJob grpc-example/grpc-example-java test"
    name: "Run tests gRPC example (java)"
  - script:
    - useAdoptOpenJdk11
    - "bin/runSbtJob grpc-example/grpc-example-scala test"
    name: "Run tests gRPC example (scala)"

  - script:
    - useAdoptOpenJdk11
    - "shopping-cart/travis-scripts/build.sh shopping-cart/shopping-cart-java sbt"
    name: "Run tests Shopping Cart example (java/sbt)"
  - script:
    - useAdoptOpenJdk11
    - "shopping-cart/travis-scripts/build.sh shopping-cart/shopping-cart-java maven"
    name: "Run tests Shopping Cart example (java/mvn)"
  - script:
    - useAdoptOpenJdk11
    - "shopping-cart/travis-scripts/build.sh shopping-cart/shopping-cart-scala sbt"
    name: "Run tests Shopping Cart example (scala)"

  - script:
    - docker-compose -f couchbase-persistence/docker/docker-compose.yml up -d couchbase 
    - sleep 30s
    - useAdoptOpenJdk11
    - mvn -f couchbase-persistence/couchbase-persistence-java-mvn test
    name: "Run tests Couchbase Persistence (java)" 
  - script:
    - docker-compose -f couchbase-persistence/docker/docker-compose.yml up -d couchbase 
    - sleep 30s
    - useAdoptOpenJdk11
    - "bin/runSbtJob couchbase-persistence/couchbase-persistence-scala-sbt test"
    name: "Run tests Couchbase Persistence (scala)"     



stages:
  - test
  - test-java11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.m2/repository
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aa0aeda88d31fe293d4
    on_success: change
    on_failure: always
    on_start: never

